### ISSUE TITLE
tacacs client with no secret key

### ISSUE THREAD

**Issue by ragu2k8** [janicki/TACACS#11]
can we pass empty string to secret key? basically server does not have secret key configured for client communication

**Comment by janicki** [comment]
The secret key is simply one of several inputs to a MD5 hash function.  So an empty string should have not effect on the MD5 output.  After a quick look through the code, it seems the empty string should be handled fine, i.e. no exceptions.  So as long as the calculates MD5 the same way, then it should be OK.

**Comment by ragu2k8** [comment]
Thanks for response .I have build the code and try to use it without passing secret key but running into below exception
Exception in thread "main" java.io.EOFException
	at java.io.DataInputStream.readFully(DataInputStream.java:197)
	at java.io.DataInputStream.readFully(DataInputStream.java:169)
	at com.augur.tacacs.TacacsReader.readFully(TacacsReader.java:131)
	at com.augur.tacacs.Packet.readNext(Packet.java:56)
	at com.augur.tacacs.TacacsReader.run(TacacsReader.java:84)

**Comment by janicki** [comment]
That exception occurs while TACACS is trying to read a packet header (12 bytes long), but runs out of data.  This is before the secret is applied the packet's data, so I do not think this exception is related to the secret at all.  I think you will have to use Wireshark to snoop the packets that are being exchanged.  You may not be even talking to a TACACS server, or else maybe the server is sending you an error message of some sort.  Anything is possible.  You have to look at the packets at this point.  So far, I do not think there is anything wrong with the TACACS code or even the secret key.

**Comment by ragu2k8** [comment]
ok i see but when i looked at server side logs i see below error message so i was thinking something to do with empty secret key value.
TACACS: Invalid TACACS+ request packet - possibly mismatched Shared Secrets
In server side by default we are not expecting secret key from client unless we register device with secret key.

**Comment by janicki** [comment]
OK, so it looks like the server is not happy with the packet it received from our library, so the server then replies with something that our TACACS library does not like: probably an error message instead of a TACACS  response packet?

My advice is still to use Wireshark.  Use it to grab the packet being sent to the server.  (You can tell Wireshare what key to use for decrypting it as part of the protocol setup, buried in some menu.)  That will help verify that you are sending the server a packet that makes sense, and that the "" key works.  

Most importantly, if Wireshark can decrypt the packet with the empty key, then we know your server is not working correctly.  Or, if Wireshark fails to understand the packet, then something is wrong with our TACACS code, or your client... Or more likely, (since the code is proven), you are not really setting an empty key like you think?  Anyway, using Wireshark in the middle will help narrow down which side is at fault!

Again, the key is simply used to create a series of bits that mask the raw data via XOR.  It doesn't really matter if the key is 0 bytes or whatever... That's just one piece of data that goes into the MD5 digest to produce the mask. It should be perfectly fine for both client and server to skip the key (because it is zero length) while computing that mask.

**Comment by ragu2k8** [comment]
appreciate your patience and thanks for timely response again. I am setting secret key values as "" and I did try to decrypt in wireshark with empty string but no luck all i seeing malformed packet from client to server.
![tacacs_img](https://user-images.githubusercontent.com/17446630/55530294-669b2600-565a-11e9-81b0-aec3c6ff2a37.jpg)

**Comment by janicki** [comment]
Thanks for the details.  Something is definitely broken, but the question is still, "Where?"  You've eliminated the server.  That's good.  So the options are either the TACACS library or your client code.  Here are some next-step suggestions:

- Try using a non-empty secret to see if that works in Wireshark at least.  That could prove I'm wrong, and there is something broken when using an empty string.  For example, maybe the RFCs require a different encoding -- perhaps no encryption?! -- when there is effectively no secret.  I don't know, but it would be faster for you to run a Wireshark test than me set up a test area again and/or read the RFCs again... Sorry, it's been a while, so I can't jump into a simulation or remember/re-read RFCs so quickly now.  I certainly will, if other attempts are exhausted, but for now I appreciate your help testing.  I hope you understand... I have other work (with pay) that has a higher priority right now.  :-)
- Send me your source code, at least the part preparing/sending the packet.  Maybe I'll spot a misunderstanding in how you are using the API, or it will reveal a bug in the API's own assumptions.
- Send me a PCAP capture of the packet, maybe along with info about what it should look like when decryped.  Maybe I could reverse-engineer the packet to see what went wrong.

Also, one request for you: Could you tell me a bit about yourself and your project?  I'm genuinely curious about who is using the code... It makes the whole open-source effort seem worthwhile.  In the absence of financial rewards, goodwill is essential.  Plus, if you're goal is to hack my company's TACACS server, it would be nice to have fair warning, right? ;-)

**Comment by ragu2k8** [comment]
1. When i tried using "secretkey" it works fine and I am able decrypt the packet in wireshark.
2. Rest of the details will try to share.
By the way I work in IT as an Engineer and I am trying to use this code for Tacacs server infra monitoring by simulating authentication requests(not a big or complex project).

**Comment by janicki** [comment]
1. Well, that does seem to implicate a problem with this TACACS library.  I'll take a deeper look now.  Thanks for patiently doing the extra checking.
2. Thanks for the info.  Sounds good.

**Comment by janicki** [comment]
I tested with Wireshark... Unfortunately if you set no secret key, Wireshark does not attempt to decode the packet's data at all, beyond just noting that the packet contains an encrypted TACACS+ message.  And if you enter "" in Wireshark's "TACACS+ Encryption Key" field, then Wireshark literally uses two quotes as the key.  So unfortunately the Wireshark test is useless for your situation.   

So, I refreshed myself with the code... An important FYI: The TacacsClient() constructor has an "unencrypted" boolean argument.  That will affect a TACACS+ packet flag.  That argument should be (normally) false... Because you want encryption, even if the key is empty, at least the packet is obfuscated (even though it can be very easily decoded!). 

I'm wondering, do you think your server is treating the empty string the same way as Wireshark... meaning don't try to decrypt?  In that case, it may only be expecting unencrypted packets, but giving you a misleading error message about bad secrets when it sees an encrypted packet arrive?

I think you could figure that out by capturing packets from other devices in your network that successfully use your server.  If Wireshark says those packets to your server are unencrypted, then you know what the server expects.  

Or, rather than waste any more time figuring out your server, could you just set that argument to true, sending unencrypted packets with this TACACS+ library.  Even if your server is doing encryption differently (i.e. our library is somehow doing it wrong), then it won't matter...  If your intention is just to monitor the server, then that may suffice.

**Comment by ragu2k8** [comment]
Big thanks and really appreciate your help. Changing the boolean argument does the magic and it works fine now.

**Comment by janicki** [comment]
That's great!!  Hope it goes smoothly now.
